#!/bin/sh


if ! which python > /dev/null; then
   echo -e "Command python not found! Install? (y/n) \c"
   read
   if "$REPLY" = "y"; then
      yay -S python
   fi
fi

mkdir $HOME/.boreaSSH

test -e $HOME/.zshrc && cat - << EOF >> $HOME/.zshrc
PATH=$PATH:$HOME/.boreaSSH
EOF

test -e $HOME/.bashrc && cat - << EOF >> $HOME/.bashrc
PATH=$PATH:$HOME/.boreaSSH
EOF

cp -r * $HOME/.boreaSSH

pip install pysftp
